#!/usr/bin/env bash

#SBATCH --cpus-per-task=1
#SBATCH --mem=40G
#SBATCH --time=04:00:00
#SBATCH --job-name=jellyfish_kmercount
#SBATCH --mail-user=anmol.ratan@students.unibe.ch
#SBATCH --mail-type=end
#SBATCH --output=/data/users/aratan/assembly_annotation_course/output_jelly_%j.o
#SBATCH --error=/data/users/aratan/assembly_annotation_course/error_jelly_%j.e
#SBATCH --partition=pibu_el8

WORKDIR=/data/users/aratan/assembly_annotation_course/fastp_filtered/
cd $WORKDIR

module load Jellyfish/2.3.0-GCC-10.3.0

jellyfish count -C -m 21 -s 5G -t 4 <(zcat *.fastq.gz) -o reads.jf

jellyfish histo -t 4 reads.jf > reads.histo

