#!/usr/bin/env bash

#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=1-00:00:00
#SBATCH --mail-user=anmol.ratan@students.unibe.ch
#SBATCH --mail-type=end
#SBATCH --job-name=flye_genome_assembly
#SBATCH --output=/data/users/aratan/assembly_annotation_course/assemblies/flye/output_flye_%j.o
#SBATCH --error=/data/users/aratan/assembly_annotation_course/assemblies/flye/error_flye_%j.e
#SBATCH --partition=pibu_el8
 


WORKDIR=/data/users/aratan/assembly_annotation_course/fastp_filtered
cd $WORKDIR

mkdir -p assemblies/flye

OUTPUTDIR=/data/users/aratan/assembly_annotation_course/assemblies/flye

#use flye container to assemble genome
apptainer exec \
--bind $WORKDIR:$WORKDIR --bind $OUTPUTDIR:$OUTPUTDIR \
/containers/apptainer/flye_2.9.5.sif \
flye --pacbio-hifi $WORKDIR/ERR11437335_processed.fastq.gz \
--out-dir $OUTPUTDIR
